Add files via upload

diff --git a/usr/bin/install-andtermenv b/usr/bin/install-andtermenv
--- a/usr/bin/install-andtermenv
+++ b/usr/bin/install-andtermenv
@@ -1,21 +1,24 @@
 #!/system/bin/sh
 MODDIR=/data/adb/andtermenv
 if [ -z "$1" ]; then
-echo "错误：路径不能为空";exit 1
+echo -e "\033[31mError: path cannot be empty\033[0m";exit 1
 fi
 if [ ! -e "$1" ]; then
-echo "错误：路径不存在 → $1";exit 1
+echo -e "\033[31mError: path does not exist → $1\033[0m";exit 1
 fi
 if [ ! -f "$1" ]; then
-echo "错误：这不是一个文件 → $1";exit 1
+echo -e "\033[31mError: This is not a file → $1\033[0m";exit 1
 fi
 if [ ! -w "$1" ]; then
-echo "错误：文件不可写 → $1";exit 1
+echo -e "\033[31mError: File is not writable → $1\033[0m";exit 1
 fi
 echo "
 # ===andterm_env===
 export PATH=${MODDIR}/usr/bin:\$PATH
 export LD_LIBRARY_PATH=${MODDIR}/usr/lib:\$LD_LIBRARY_PATH
+export HOME=/data/adb/andtermenv/home
+if [ \$(id -u) -ne 0 ];then
+su -c version-andtermenv;su;fi
 # ---andterm_env---
 " >> "$1"
-echo '已添加环境变量配置'
+echo -e "\033[92mEnvironment variable configuration has been added.\033[0m"
diff --git a/usr/bin/uninstall-andtermenv b/usr/bin/uninstall-andtermenv
--- a/usr/bin/uninstall-andtermenv
+++ b/usr/bin/uninstall-andtermenv
@@ -1,15 +1,15 @@
 #!/system/bin/sh
 if [ -z "$1" ]; then
-echo "错误：路径不能为空";exit 1
+echo -e "\033[31mError: path cannot be empty\033[0m";exit 1
 fi
 if [ ! -e "$1" ]; then
-echo "错误：路径不存在 → $1";exit 1
+echo -e "\033[31mError: path does not exist → $1\033[0m";exit 1
 fi
 if [ ! -f "$1" ]; then
-echo "错误：这不是一个文件 → $1";exit 1
+echo -e "\033[31mError: This is not a file → $1\033[0m";exit 1
 fi
 if [ ! -w "$1" ]; then
-echo "错误：文件不可写 → $1";exit 1
+echo -e "\033[31mError: File is not writable → $1\033[0m";exit 1
 fi
 sed -i '/^# ===andterm_env===/,/^# ---andterm_env---/d' "$1"
-echo '已移除环境变量配置'
+echo -e "\033[93mEnvironment variable configuration has been removed\033[0m"
